#
# This file configures the New Relic Agent.
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration

common: &default_settings
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  app_name: <%= ENV.fetch("HEROKU_APP_NAME", "Never miss pilates") %>
  log_level: info

development:
  monitor_mode: false

test:
  monitor_mode: false

production:
  <<: *default_settings
