# Configuration file for Sidekiq.
# https://github.com/sidekiq/sidekiq/blob/main/examples/config.yml
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.

# Scheduled jobs: https://github.com/sidekiq-scheduler/sidekiq-scheduler

---
:queues:
  - high
  - default
:scheduler:
  :dynamic: true
  :enabled: false # todo. enable it
  :schedule:
    scraper_enqueuer:
      cron: "0/10 * * * *" # Every 10 minutes
      class: "Enqueuer::Worker"
      queue: default
