# Configuration file for Sidekiq.
# https://github.com/sidekiq/sidekiq/blob/main/examples/config.yml
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.

# Scheduled jobs: https://github.com/sidekiq-scheduler/sidekiq-scheduler

---
:queues:
  - high
  - default
:scheduler:
  :dynamic: true
  :enabled: true
  :schedule:
    crc_booker:
      cron: "0,1,5,10,15,30,45 * * * *"
      class: "CRC::AllBooker::Worker"
      queue: default
